---
title: "Build Genotype File"
author: "Griffin Tibbitts"
date: '2023-04-10'
output: html_document
acknowledgement: Adapted from code written by K. Nevola and C. Lary
---

```{r}
rm(list = ls())
library(dplyr)
library(tidyverse)
library(gtsummary)
```

```{r}
# IMPORTANT
# Lumbar spine was not found to be significant for any snps
# To reduce data size, only the femoral neck data will be run here

FN_Pheno <- read.csv('/work/larylab/Griffin_Stuff/Griffin_Framingham/data/FULL_POWER_Femoral_Neck_Pheno_Data.csv')

# Filtered genotype files created from workflow described by K. Nevola
genotype_files<- list.files(path = '/work/larylab/Griffin_Stuff/Griffin_Framingham/data/TargetGenes', 
                            pattern = "_filtered_genotype.RData")

# Create single data frame with snps labeled by gene
# SNP position is given for the Ch37 human genome build
setwd('/work/larylab/Griffin_Stuff/Griffin_Framingham/data/TargetGenes')
df <- NULL
for (i in genotype_files){
  print(i)
  load(i)
  gene <- merge(tidy$gt, tidy$fix, by = "POS")
  gene$Gene <- gsub(x = i, pattern = "_.*",replacement ="")
  df <- rbind(df,gene)
}
fn_all_genes_pheno <- merge(df, FN_Pheno, by.x = "Indiv", by.y = "shareid")
head(fn_all_genes_pheno)
```

```{r}
# Quick check of data parameters
# Number of unique SNPs (863)
length(unique(fn_all_genes_pheno$POS)) 

# Number of people in genotype table (1028)
length(unique(fn_all_genes_pheno$Indiv)) 

# Number of People in merged table (1028)
length(unique(filter(fn_all_genes_pheno, SEX == 'Female')$Indiv)) 
```

```{r}
# Nest data
fn_pheno_snp <- within(fn_all_genes_pheno, Genotype <- relevel(Genotype, ref = "normal"))
fn_pheno_snp_pos<- fn_pheno_snp %>% group_by(.,POS,Gene) %>% nest()
```

```{r}
# Full power signifies both cohorts, FN femoral neck. 
save(fn_pheno_snp_pos, file = "/work/larylab/Griffin_Stuff/Griffin_Framingham/data/FULL_POWER_FN_CandidateGenes.RData")
```

```{r}
cohort <- fn_all_genes_pheno %>% filter(POS == 240243682, SEX == 'Female') 
tbl_summary(cohort, include = c(BB, AGE, BMI, HGT, EST, f6_7nbmd))
```
