---
title: "Build Longitudinal Phenotype - Genotype File"
author: "Griffin Tibbitts"
date: '2023-04-10'
output: html_document
acknowledgement: Adapted from code written by K. Nevola and C. Lary
---
```{r}
rm(list = ls())
library(dplyr)
library(tidyverse)
library(gtsummary)
```

```{r}
# Read Files
# dbGAP files consist of two consent groups which must be merged for each variable

# Exam 6 bmd files
bmd_ex6_c1 <- read.table(gzfile('/work/larylab/dbgap/data9/phs000007.v33.pht000169.v8.p14.c1.t_bmd_ex07_1_0104s.HMB-IRB-MDS.txt.gz'),
                      sep = "\t", header = T)
bmd_ex6_c2 <- read.table(gzfile('/work/larylab/dbgap/data9/phs000007.v33.pht000169.v8.p14.c2.t_bmd_ex07_1_0104s.HMB-IRB-NPU-MDS.txt.gz'), sep = "\t", header = T)
bmd_ex6 = rbind(bmd_ex6_c1, bmd_ex6_c2)

# Exam 8 BMD
bmd_ex8_c1 <- read.table(gzfile('/work/larylab/dbgap/data9/phs000007.v33.pht003096.v4.p14.c1.t_bmdhs_2008_1_0748s.HMB-IRB-MDS.txt.gz'),
                      sep = "\t", header = T) 
bmd_ex8_c2 <- read.table(gzfile('/work/larylab/dbgap/data9/phs000007.v33.pht003096.v4.p14.c2.t_bmdhs_2008_1_0748s.HMB-IRB-NPU-MDS.txt.gz'), 
                         sep = "\t", header = T) 
bmd_ex8 <- rbind(bmd_ex8_c1, bmd_ex8_c2)

# Estrogen Use
est_c1 <- read.delim(gzfile("/work/larylab/dbgap/data9/phs000007.v33.pht000307.v10.p14.c1.meno1_8s.HMB-IRB-MDS.txt.gz"),
                  skip=10,header=T,stringsAsFactors = F)
est_c2 <- read.delim(gzfile("/work/larylab/dbgap/data9/phs000007.v33.pht000307.v10.p14.c2.meno1_8s.HMB-IRB-NPU-MDS.txt.gz"),
                  skip=10,header=T,stringsAsFactors = F)
est <- rbind(est_c1, est_c2)

# Clean Estrogen use data to account for 'maybes'
est <- est %>%
  mutate(EST6_New = ifelse(is.na(EST6), "missing", ifelse(EST6 == 1, 'yes', 'no')),
         EST8_New = ifelse(is.na(EST8), "missing", ifelse(EST8 == 1, 'yes', 'no'))) %>%
  select(-EST6, -EST8) %>%
  rename(EST6 = EST6_New,
         EST8 = EST8_New)

# Medications at exam 6
meds_ex6_c1 <- read.table(gzfile("/work/larylab/dbgap/data9/phs000007.v33.pht000035.v11.p14.c1.ex1_6s.HMB-IRB-MDS.txt.gz"),
                       sep = "\t", header = T)
meds_ex6_c2 <- read.table(gzfile("/work/larylab/dbgap/data9/phs000007.v33.pht000035.v11.p14.c2.ex1_6s.HMB-IRB-NPU-MDS.txt.gz"),
                       sep = "\t", header = T)
meds_ex6 <- rbind(meds_ex6_c1, meds_ex6_c2)

# exam dates, age and sex covariates
cov_c1 <- read.delim(gzfile("/work/larylab/dbgap/data9/phs000007.v33.pht006027.v4.p14.c1.vr_wkthru_ex09_1_1001s.HMB-IRB-MDS.txt.gz"),
                  skip=10,header=T,stringsAsFactors = F)
cov_c2 <- read.delim(gzfile("/work/larylab/dbgap/data9/phs000007.v33.pht006027.v4.p14.c2.vr_wkthru_ex09_1_1001s.HMB-IRB-NPU-MDS.txt.gz"),
                  skip=10,header=T,stringsAsFactors = F)
cov <- rbind(cov_c1, cov_c2)
```
```{r}
head(cov)
```

```{r}
# Extract BMD data at each exam and merge into one table
bmd_ex6 <- bmd_ex6 %>% dplyr::select(., shareid, f6_7nbmd, s6_7l24bd, f6_7scdt, s6_7scdt)
bmd_ex8 <- bmd_ex8 %>% dplyr::select(., shareid, f7_5nbmd, s7_5l24bd, f7_5scdt, s7_5scdt,
                                     f8cbnbmd,s8cbl24bd,f8cbscdt,s8cbscdt)
bmd_ex678 <- merge(bmd_ex6,bmd_ex8,by="shareid",all.x=T)
# Extract BB use from exam 6 medication files
bb_ex6 <- meds_ex6 %>% dplyr::select(., shareid, F190)
bb_ex6$BB6[bb_ex6$F190 == 2] <- "Yes, Not Now"
bb_ex6$BB6[bb_ex6$F190 == 0] <- "No"
bb_ex6$BB6[bb_ex6$F190 == 1] <- "Yes, Now"
bb_ex6$BB6[bb_ex6$F190 == 3] <- "Maybe"
bb_ex6$BB6 <- as.factor(bb_ex6$BB6)
bb_ex6$BB <- ifelse(bb_ex6$F190 == 1,1,
                       ifelse(bb_ex6$F190 ==0,0,NA))

# Merge all covariates from their respective tables into one covariate table
cov <- merge(cov,bb_ex6,by="shareid",all.x=T)
cov <- merge(cov,est,by="shareid",all.x=T)

# Merge covariates with BMD data, clean data, and create columns for
# longitudinal data, here as difference from exam 6 to 8 normalized to a per-year
# delta BMD.
bmd_ex678cov <- merge(bmd_ex678,cov,by="shareid", all.x=TRUE) 

long_bmd_ex678cov <- bmd_ex678cov %>% # 22 missing ex6 FN and 25 ex6 LS
  mutate(SEX = ifelse(SEX==1,"Male",ifelse(SEX==2,"Female",NA))) %>%
  mutate(BB6 = ifelse(BB==1,"Yes",ifelse(BB==0,"No",NA)))  %>%
  dplyr::select(-BB) %>%
  mutate(bmd6FN = ifelse(is.na(f6_7nbmd),"no","yes"))  %>%
  mutate(bmd6LS = ifelse(is.na(s6_7l24bd),"no","yes"))  %>%
  mutate(bmd67FN = ifelse(is.na(f6_7nbmd) | is.na(f7_5nbmd),"no","yes"))  %>%
  mutate(bmd67LS = ifelse(is.na(s6_7l24bd) | is.na(s7_5l24bd),"no","yes"))  %>%
  mutate(bmd68FN = ifelse(is.na(f6_7nbmd) | is.na(f8cbnbmd),"no","yes"))  %>%
  mutate(bmd68LS = ifelse(is.na(s6_7l24bd) | is.na(s8cbl24bd),"no","yes")) %>%
  mutate(FNdelta67 = f7_5nbmd-f6_7nbmd) %>%
  mutate(FNdelta68 = f8cbnbmd-f6_7nbmd) %>%
  mutate(LSdelta67 = s7_5l24bd-s6_7l24bd) %>%
  mutate(LSdelta68 = s8cbl24bd-s6_7l24bd) %>%
  mutate(FN67timedif = (f7_5scdt-f6_7scdt)/365.25) %>%
  mutate(LS67timedif = (s7_5scdt-s6_7scdt)/365.25) %>%
  mutate(FN68timedif = (f8cbscdt-f6_7scdt)/365.25) %>%
  mutate(LS68timedif = (s8cbscdt-s6_7scdt)/365.25) %>%
  mutate(FNperyear67 = FNdelta67/FN67timedif) %>%
  mutate(FNperyear68 = FNdelta68/FN68timedif) %>%
  mutate(LSperyear67 = LSdelta67/LS67timedif) %>%
  mutate(LSperyear68 = LSdelta68/LS68timedif) %>%
  mutate(LSperyear = ifelse(is.na(LSperyear68),LSperyear67,LSperyear68)) %>%
  mutate(FNperyear = ifelse(is.na(FNperyear68),FNperyear67,FNperyear68)) %>%
  mutate(SEX6 = SEX) %>%
  mutate(SEX = ifelse(!is.na(SEX),SEX,ifelse(!is.na(SEX6),SEX6,NA))) %>%
  dplyr::select(-SEX6) %>%
  dplyr::select(-f8cbnbmd,-s8cbl24bd) %>%
  filter(!is.na(BB6)) %>%
  filter(!is.na(BMI6))
```
```{r}
head(long_bmd_ex678cov)
```

```{r}
# Check parameters of the merged dataset
length(which(is.na(bmd_ex678cov$BMI6))) # 0
length(which(is.na(bmd_ex678cov$HGT6))) # 0
length(which(is.na(bmd_ex678cov$AGE6))) # 0
length(which(is.na(bmd_ex678cov$EST6_New))) # 0 
length(which(is.na(bmd_ex678cov$BB6))) # 0
length(which(is.na(bmd_ex678cov$f6_7nbmd))) # 14
length(which(is.na(bmd_ex678cov$s6_7l24bd))) # 17
table(bmd_ex678cov$EST6, exclude = F) # missing no  yes NA
                                      # 1       924 368 1017
```

```{r}
# At this point, to account for missing values, create two output files. 
# One for femoral neck BMD and the other for Lumbar Spine BMD

femoral_neck <- long_bmd_ex678cov %>%
  select(shareid, f6_7nbmd, SEX, AGE6, BMI6, HGT6, EST6, BB6, FNperyear) %>%
  filter(!is.na(FNperyear)) %>%
  filter(SEX == 'Female')%>%
  rename(AGE = AGE6, BMI = BMI6, HGT = HGT6, EST = EST6, BB = BB6)

lumbar_spine <- long_bmd_ex678cov %>%
  select(shareid, s6_7l24bd, SEX, AGE6, BMI6, HGT6, EST6, BB6, LSperyear) %>%
  filter(!is.na(LSperyear)) %>%
  filter(SEX == 'Female')%>%
  rename(AGE = AGE6, BMI = BMI6, HGT = HGT6, EST = EST6, BB = BB6)
```

```{r}
head(femoral_neck)
```
```{r}
# Not the official summary since 49 don't have genotype data.
tbl_summary(femoral_neck, include = c(AGE, BMI, HGT, EST, BB, FNperyear, f6_7nbmd))
```

```{r}
write.csv(femoral_neck, '/work/larylab/Griffin_Stuff/Griffin_Framingham/data/FULL_POWER_Femoral_Neck_Pheno_Data.csv')
write.csv(lumbar_spine, '/work/larylab/Griffin_Stuff/Griffin_Framingham/data/FULL_POWER_Lumbar_Spine_Pheno_Data.csv')
```
