---
title: "Merge Framingham Results with Mayo Nomenclature"
author: "Griffin Tibbitts"
date: '2023-04-10'
output: html_document
---

```{r}
rm(list = ls())
library(dplyr)
library(tidyr)
library(stringr)
```

```{r}
results <- read.csv('/work/larylab/Griffin_Stuff/Griffin_Framingham/results/AllSNP_sig_interaction_LMEKIN_female_v5.csv')

# Master list of all identified SNPs with their different nomenclatures
mayo <- read.csv('/work/larylab/Griffin_Stuff/Griffin_Mayo/data/mayo_fram_snp_master_list.csv')

# Lookup file with Mayo nomenclature(s)
lookup <- read.csv('/work/larylab/Mayo/data/Lookup.csv')

# Geno-pheno file
load('/work/larylab/Griffin_Stuff/Griffin_Framingham/data/CandidateGenes.RData')
```

```{r}
# Get the reference and alternate alleles for each snp from the original geno-pheno file
alleles <- unnest(pheno_snp_pos, cols = c(data)) %>%
  select(POS, REF, ALT) %>%
  rename(FRef = REF, FAlt = ALT) %>%
  distinct()
alleles
```

```{r}
# Merge to give each result its reference and alternate alleles
relevant_merged <- merge(results, alleles, by = 'POS') %>%
  rename(Gene = Gene.x) %>%
  select(-`Gene.y`) %>%

  mutate(POS = as.numeric(POS))
relevant_merged
```

```{r}
mayo1 <- mayo %>%
  distinct() %>%
  mutate(MRef = ch38.reference.allele,
         MAlt = ch38.alternate.allele,
         MAlt = case_when(MAlt == '' ~ NA,
                          TRUE ~ MAlt)) %>%
  rename(POS = ch37) %>%
  select(rsid, POS, ch38, MRef, MAlt) %>%
  mutate(POS = as.numeric(POS))
```

```{r}
merge_with_mayo <- merge(relevant_merged, mayo1, by = 'POS', all.x = T) %>%
  
  # Remove duplicate entries (some happen)
  distinct() %>%
  
  # Merge with the lookup file
  merge(lookup, by = 'rsid', all = T) %>%
  filter(!is.na(n)) %>%
  
  # Remove unnecessary lookup values
  select(-mayo, -SNP, -Gene.y, -old_POS, -SNP.1, -mayo2, -pos) %>%
  
  # Create old vs new position columns
  mutate(NewPOS = gsub("^.*:","", ch38), .after = POS) %>%
  select(-ch38) %>% 
  rename(ch37 = POS, Gene = Gene.x, ch38 = NewPOS) %>%
  
  # Label with source, drug column and BMD_Site column
  mutate(Source = 'Fram', Drug = "Any BB", BMD_Site = 'Total Body')

write.csv(merge_with_mayo, '/work/larylab/Griffin_Stuff/Griffin_Mayo/results/merged_with_mayo_v5.csv')
```

